version: "3.8"

services:
  front:
    image: nginx:latest
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front:/usr/share/nginx/html
      - shared_data:/usr/share/nginx/html/photo

  # admin:
  #   image: nginx:latest
  #   container_name: admin
  #   build: ./front/admin
  #   ports:
  #     - "81:81"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./front:/usr/share/nginx/html

  back:
    build: ./back
    container_name: backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_URI: ${DB_URI}
      ROOT_LOGIN: ${ROOT_LOGIN}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "5000:5000"
    volumes:
      - ./data/back:/data/back
      - shared_data:/Cars-Fun-Site/photo

  mongo:
    image: "mongo:latest"
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

volumes:
  shared_data:
